namespace Shrimp.Pdf
#nowarn "0104"
open iText.IO.Font
open System.IO
open Resources
open Shrimp.FSharp.Plus

type RegisterableFont =
    { PdfEncodings: string
      File: FsFileInfo 
      FontFamily: string }
with 
    member x.Path = x.File.Path

    member x.LoggingText = x.FontFamily


type CommonFontWeight =
    | Light = 0
    | Regular = 1
    | Bold = 2

/// PostScript FontNames
module FontNames =
    
    /// PostScript FontNames
    module Query =  

        /// PostScript FontNames
        type FontNames =
            | ``301-CAI978`` = 1
            | ``A1 MinchoStd-Bold`` = 2
            | ``aaaz-`` = 3
            | ``ACaslonPro-Bold`` = 4
            | ``ACaslonPro-Boldltalic`` = 5
            | ``ACaslonPro-ltalic`` = 6
            | ``ACaslonPro-Regular`` = 7
            | ``ACaslonPro-Semibold`` = 8
            | ``ACaslonPro-Semiboldltalic`` = 9
            | ``AcuminProWide-ExtraLight`` = 10
            | ``Adlinnaka-LightCondensed`` = 11
            | ``AdobeArabic-Bold`` = 12
            | ``AdobeArabic-Boldltalic`` = 13
            | ``AdobeArabic-ltalic`` = 14
            | ``AdobeArabic-Regular`` = 15
            | ``AdobeDevanagari-Bold`` = 16
            | ``AdobeDevanagari-Boldltalic`` = 17
            | ``AdobeDevanagari-ltalic`` = 18
            | ``AdobeDevanaqari-ltalic`` = 19
            | ``AdobeDevanagari-Regular`` = 20
            | ``AdobeFangsongStd-Regular`` = 21
            | ``AdobeFanHeitiStd-Bold`` = 22
            | ``AdobeGothicStd-Bold`` = 23
            | ``AdobeGothicStd-Light`` = 24
            | ``AdobeHebrew-Bold`` = 25
            | ``AdobeHebrew-Boldltalic`` = 26
            | ``AdobeHebrew-ltalic`` = 27
            | ``AdobeHebrew-Regular`` = 28
            | ``AdobeHeitiStd-Regular`` = 29
            | ``AdobeKaitiStd-Regular`` = 30
            | ``AdobeMingStd-Light`` = 31
            | ``AdobeMyungjoStd-Medium`` = 32
            | ``AdobeNaskh-Medium`` = 33
            | ``AdobePiStd`` = 34
            | ``AdobeSongStd-Light`` = 35
            | ``AdobeThai-Bold`` = 36
            | ``AdobeThai-Boldltalic`` = 37
            | ``AdobeThai-ltalic`` = 38
            | ``AdobeThai-Regular`` = 39
            | ``AGaramondPro-Bold`` = 40
            | ``AGaramondPro-Boldltalic`` = 41
            | ``AGaramondPro-ltalic`` = 42
            | ``AGaramondPro-RequIar`` = 43
            | ``AgencyFB-Bold`` = 44
            | ``AgencyFB-Reg`` = 45
            | ``AkashiStd-Light`` = 46
            | ``Algerian`` = 47
            | ``AlternateGothicEF-NoTwo`` = 48
            | ``AmasisMT-Medium`` = 49
            | ``Amfibia-DemiBold`` = 50
            | ``AnitoStd-Inline`` = 51
            | ``AnitoStd-L`` = 52
            | ``AnitoStd-M`` = 53
            | ``AnitoStd-Relief`` = 54
            | ``AnticCezannePro-DB`` = 55
            | ``AnticCezannePro-M`` = 56
            | ``AraletStd-DB`` = 57
            | ``Archia-SemiBold`` = 58
            | ``Arial-Black`` = 59
            | ``Arial-BoldltalicMT`` = 60
            | ``Arial-BoldMT`` = 61
            | ``Arial,Bold`` = 610
            | ``ArialEnllnicodeBold`` = 62
            | ``Arial-ltalicMT`` = 63
            | ``Arial-Lgt`` = 64
            | ``ArialMT`` = 65
            |    Arial = 6500
            | ``ArialNarrow`` = 66
            | ``ArialNarrow-Bold`` = 67
            | ``ArialNarrow-Boldltalic`` = 68
            | ``ArialNarrow-ltalic`` = 69
            | ``ArialRoundedMTBold`` = 70
            | ``ArialUnicodeMS`` = 71
            | ``ArialUnicodeMS-Bold`` = 72
            | ``AtkinsCondMedium-Regular`` = 73
            | ``AudiowidePro-Regular`` = 74
            | ``Audiowide-Regular`` = 75
            | ``Bahnschrift`` = 76
            | ``Balboa-Medium`` = 77
            | ``BaskOldFace`` = 78
            | ``Bauhaus93`` = 79
            | ``BebasNeue-Regular`` = 80
            | ``BellMT`` = 81
            | ``BellMTBold`` = 82
            | ``BellMTItalic`` = 83
            | ``BerlinSansFB-Bold`` = 84
            | ``BerlinSansFBDemi-Bold`` = 85
            | ``BerlinSansFB-Reg`` = 86
            | ``BernardMT-Condensed`` = 87
            | ``BirchStd`` = 88
            | ``Bison-Bold`` = 89
            | ``BlackadderlTC-Regular`` = 90
            | ``BlackoakStd`` = 91
            | ``BodoniBT-Bold`` = 92
            | ``BodoniBT-Boldltalic`` = 93
            | ``BodoniBT-Book`` = 94
            | ``BodoniBT-Bookltalic`` = 95
            | ``BodoniMT`` = 96
            | ``BodoniMTBlack`` = 97
            | ``BodoniMTBlack-ltalic`` = 98
            | ``BodoniMT-Bold`` = 99
            | ``BodoniMT-Boldltalic`` = 100
            | ``BodoniMTCondensed`` = 101
            | ``BodoniMTCondensed-Bold`` = 102
            | ``BodoniMTCondensed-Boldltalic`` = 103
            | ``BodoniMTCondensed-ltalic`` = 104
            | ``BodoniMT-ltalic`` = 105
            | ``BodoniMTPosterCompressed`` = 106
            | ``BookAntiqua`` = 107
            | ``BookAntiqua-Bold`` = 108
            | ``BookAntiqua-Boldltalic`` = 109
            | ``BookAntiqua-ltalic`` = 110
            | ``BookmanOldStyle`` = 111
            | ``BookmanOldStyle-Bold`` = 112
            | ``BookmanOldStyle-Boldltalic`` = 113
            | ``BookmanOldStyle-ltalic`` = 114
            | ``BookshelfSymbolSeven`` = 115
            | ``BradleyHandITC`` = 116
            | ``BritannicBold`` = 117
            | ``Broadway`` = 118
            | ``BrushScriptMT`` = 119
            | ``BrushScriptStd`` = 120
            | ``BudoStd-L`` = 121
            | ``Calibri`` = 122
            | ``Calibri-Bold`` = 123
            | ``Calibri-Boldltalic`` = 124
            | ``Calibri-ltalic`` = 125
            | ``Calibri-Light`` = 126
            | ``Calibri-Lightltalic`` = 127
            | ``CalifornianFB-Bold`` = 128
            | ``CalifornianFB-ltalic`` = 129
            | ``CalifornianFB-Reg`` = 130
            | ``CalisMTBol`` = 131
            | ``CalistoMT`` = 132
            | ``CalistoMT-Boldltalic`` = 133
            | ``CalistoMT-ltalic`` = 134
            | ``Cambria`` = 135
            | ``Cambria-Bold`` = 136
            | ``Cambria-Boldltalic`` = 137
            | ``Cambria-Italic`` = 138
            | ``CambriaMath`` = 139
            | ``Candara`` = 140
            | ``Candara-Bold`` = 141
            | ``Candara-Boldltalic`` = 142
            | ``Candara-ltalic`` = 143
            | ``Candara-Light`` = 144
            | ``Candara-Lightltalic`` = 145
            | ``CaratStd-UB`` = 146
            | ``CascadiaCode-Roman`` = 147
            | ``CascadiaMono-Roman`` = 148
            | ``Castellar`` = 149
            | ``Centaur`` = 150
            | ``Century`` = 151
            | ``Century725BT-RomanCondensed`` = 152
            | ``Century751 BT-BoldB`` = 153
            | ``Century751 BT-BoldltalicB`` = 154
            | ``Century751 BT-ltalicB`` = 155
            | ``Century751 BT-No2ltalicB`` = 156
            | ``Century751 BT-RomanB`` = 157
            | ``Century751 BT-RomanNo2B`` = 158
            | ``Century751 BT-SemiBold`` = 159
            | ``Century751 BT-SemiBoldltalicB`` = 160
            | ``CenturyGothic`` = 161
            | ``CenturyGothic-Bold`` = 162
            | ``CenturyGothic-Boldltalic`` = 163
            | ``CenturyGothic-ltalic`` = 164
            | ``CenturySchlbkCyrillicBT-Bold`` = 165
            | ``CenturySchlbkCyrillicBT-Boldlt`` = 166
            | ``CenturySchlbkCyrillicBT-ltalic`` = 167
            | ``CenturySchlbkCyrillicBT-Roman`` = 168
            | ``CenturySchoolbook`` = 169
            | ``CenturySchoolbook-Bold`` = 170
            | ``CenturySchoolbook-Boldltalic`` = 171
            | ``CenturySchoolbook-ltalic`` = 172
            | ``CeraRoundPro-Light`` = 173
            | ``CezanneBokutohPro-B`` = 174
            | ``CezanneBokutohPro-DB`` = 175
            | ``CezanneBokutohPro-EB`` = 176
            | ``CezanneBokutohPro-M`` = 177
            | ``CezannePro-B`` = 178
            | ``CezannePro-DB`` = 179
            | ``CezannePro-EB`` = 180
            | ``CezannePro-M`` = 181
            | ``CezanneProN-B`` = 182
            | ``CezanneProN-DB`` = 183
            | ``CezanneProN-EB`` = 184
            | ``CezanneProN-M`` = 185
            | ``Chamois`` = 186
            | ``Champagne&Limousines`` = 187
            | ``ChaparralPro-Bold`` = 188
            | ``ChaparralPro-Boldlt`` = 189
            | ``ChaparralPro-ltalic`` = 190
            | ``ChaparralPro-Lightlt`` = 191
            | ``ChaparralPro-Regular`` = 192
            | ``CharlemagneStd-Bold`` = 193
            | ``ChiaroStd-B`` = 194
            | ``Chiller-Regular`` = 195
            | ``ClarendonBT-Black`` = 196
            | ``ClarendonBT-Bold`` = 197
            | ``ClarendonBT-Light`` = 198
            | ``ClarendonBT-Roman`` = 199
            | ``Code-Pro-LC`` = 200
            | ``ColonnaMT`` = 201
            | ``CometStd-B`` = 202
            | ``ComicMysteryStd-DB`` = 203
            | ``ComicReggaeStd-B`` = 204
            | ``ComicSansMS`` = 205
            | ``ComicSansMS-Bold`` = 206
            | ``ComicSansMS-Boldltalic`` = 207
            | ``ComicSansMS-ltalic`` = 208
            | ``Consolas`` = 209
            | ``Consolas-Bold`` = 210
            | ``Consolas-Boldltalic`` = 211
            | ``Consolas-ltalic`` = 212
            | ``Constantia`` = 213
            | ``Constantia-Bold`` = 214
            | ``Constantia-Boldltalic`` = 215
            | ``Constantia-ltalic`` = 216
            | ``CooperBlack`` = 217
            | ``CooperBlackStd`` = 218
            | ``CooperBlackStd-ltalic`` = 219
            | ``CopperplateGothic-Bold`` = 220
            | ``CopperplateGothic-Light`` = 221
            | ``Corbel`` = 222
            | ``Corbel-Bold`` = 223
            | ``Corbel-Boldltalic`` = 224
            | ``Corbel-Italic`` = 225
            | ``CorbelLight`` = 226
            | ``CorbelLight-ltalic`` = 227
            | ``CourierNewPS-BoldltalicMT`` = 228
            | ``CourierNewPS-BoldMT`` = 229
            | ``CourierNewPS-ltalicMT`` = 230
            | ``CourierNewPSMT`` = 231
            | ``CourierStd`` = 232
            | ``CourierStd-Bold`` = 233
            | ``CourierStd-BoldOblique`` = 234
            | ``CourierStd-Oblique`` = 235
            | ``CurlzMT`` = 236
            | ``DBYamX-Bold`` = 237
            | ``DejaVuSansMono`` = 238
            | ``DejaVuSansMono-Bold`` = 239
            | ``DejaVuSansMono-BoldOblique`` = 240
            | ``DejaVuSansMono-Oblique`` = 241
            | ``DengXian`` = 242
            | ``DengXian-Bold`` = 243
            | ``DengXian-Light`` = 244
            | ``DeVinneBT-Text`` = 245
            | ``DFGothic-EB-WIN-RKSJ-H`` = 246
            | ``DFKaiSho-SB-WIN-RKSJ-H`` = 247
            | ``DFMincho-SU-WIN-RKSJ-H`` = 248
            | ``DFMincho-UB-WIN-RKSJ-H`` = 249
            | ``DFMincho-W5-WIN-RKSJ-H`` = 250
            | ``DFPOP1-W9-WIN-RKSJ-H`` = 251
            | ``DFYuan-Bd-HK-BF`` = 252
            | ``DFYuan-Bd-HKP-BF`` = 253
            | ``DFYuanHKBD`` = 254
            | ``DFYuanLightHKBD`` = 255
            | ``DIN`` = 256
            | ``DIN-Bold`` = 257
            | ``DotGothicI 2Std-M`` = 258
            | ``DotGothicI 6Std-M`` = 259
            | ``DotMinchol 2Std-M`` = 260
            | ``DotMinchol 6Std-M`` = 261
            | ``Dubai-Bold`` = 262
            | ``Dubai-Light`` = 263
            | ``Dubai-Medium`` = 264
            | ``Dubai-Regular`` = 265
            | ``Ebrima`` = 266
            | ``Ebrima-Bold`` = 267
            | ``EdwardianScriptITC`` = 268
            | ``Elephant-Italic`` = 269
            | ``Elephant-Regular`` = 270
            | ``EmbassyBT-Regular`` = 271
            | ``EnfocusSans`` = 272
            | ``EnfocusSans-Bold`` = 273
            | ``EnfocusSans-BoldOblique`` = 274
            | ``EnfocusSansMono`` = 275
            | ``EnfocusSansMono-Bold`` = 276
            | ``EnfocusSansMono-BoldOblique`` = 277
            | ``EnfocusSansMono-Oblique`` = 278
            | ``EnfocusSans-Oblique`` = 279
            | ``EnfocusSerif`` = 280
            | ``EnfocusSerif-Bold`` = 281
            | ``EnfocusSerif-Boldltalic`` = 282
            | ``EnfocusSerif-ltalic`` = 283
            | ``EnfocusSym`` = 284
            | ``EnfocusZapf`` = 285
            | ``EngraversGothicBT-Regular`` = 286
            | ``EngraversMT`` = 287
            | ``ErasITC-Bold`` = 288
            | ``ErasITC-Demi`` = 289
            | ``ErasITC-Light`` = 290
            | ``ErasITC-Medium`` = 291
            | ``Exotic350BT-Bold`` = 292
            | ``Exotic350BT-DemiBold`` = 293
            | ``FangSong`` = 294
            | ``FelixTitlingMT`` = 295
            | ``FolkPro-Bold`` = 296
            | ``FolkPro-Heavy`` = 297
            | ``FolkPro-Medium`` = 298
            | ``FolkPro-Regular`` = 299
            | ``FootlightMTLight`` = 300
            | ``ForteMT`` = 301
            | ``FranklinGothic-Book`` = 302
            | ``FranklinGothic-Bookltalic`` = 303
            | ``FranklinGothic-Demi`` = 304
            | ``FranklinGothic-DemiCond`` = 305
            | ``FranklinGothic-Demiltalic`` = 306
            | ``FranklinGothic-Heavy`` = 307
            | ``FranklinGothic-Heavyltalic`` = 308
            | ``FranklinGothic-Medium`` = 309
            | ``FranklinGothic-MediumCond`` = 310
            | ``FranklinGothic-Mediumltalic`` = 311
            | ``Freehand521 BT-RegularC`` = 312
            | ``FreestyleScript-Regular`` = 313
            | ``FrenchScriptMT`` = 314
            | ``FutoGoB101Pr5-Bold`` = 315
            | ``FutoGoBI 01 Pro-Bold`` = 316
            | ``FutoMinA101Pr5-Bold`` = 317
            | ``FutoMinAI 01 Pro-Bold`` = 318
            | ``FuturaBT-Bold`` = 319
            | ``FuturaBT-Boldltalic`` = 320
            | ``FuturaBT-Book`` = 321
            | ``FuturaBT-Bookltalic`` = 322
            | ``FuturaBT-Medium`` = 323
            | ``FuturaBT-Mediumltalic`` = 324
            | ``FuturaStd-Bold`` = 325
            | ``FuturaStd-BoldOblique`` = 326
            | ``FuturaStd-Book`` = 327
            | ``FuturaStd-BookOblique`` = 328
            | ``FuturaStd-Condensed`` = 329
            | ``FuturaStd-CondensedBold`` = 330
            | ``FuturaStd-CondensedBoldObl`` = 331
            | ``FuturaStd-CondensedExtraBd`` = 332
            | ``FuturaStd-CondensedLight`` = 333
            | ``FuturaStd-CondensedLightObl`` = 334
            | ``FuturaStd-CondensedOblique`` = 335
            | ``FuturaStd-CondExtraBoldObl`` = 336
            | ``FuturaStd-ExtraBold`` = 337
            | ``FuturaStd-ExtraBoldOblique`` = 338
            | ``FuturaStd-Heavy`` = 339
            | ``FuturaStd-HeavyOblique`` = 340
            | ``FuturaStd-Light`` = 341
            | ``FuturaStd-LightOblique`` = 342
            | ``FuturaStd-Medium`` = 343
            | ``FuturaStd-MediumOblique`` = 344
            | ``FZBSJW-GB1-0`` = 345
            | ``FZBWKSJW-GB1-0`` = 346
            | ``Gadugi`` = 347
            | ``Gadugi-Bold`` = 348
            | ``GalanoClassic-ExtraBold`` = 349
            | ``Garamond`` = 350
            | ``Garamond-Bold`` = 351
            | ``Garamond-ltalic`` = 352
            | ``Geometric212BT-BookCondensed`` = 353
            | ``Geometric212BT-HeavyCondensed`` = 354
            | ``Geometric415BT-BlackA`` = 355
            | ``Geometric706BT-BlackCondensedB`` = 356
            | ``GeometricSlab703BT-Bold`` = 357
            | ``GeometricSlab703BT-BoldCond`` = 358
            | ``GeometricSlab703BT-Boldltalic`` = 359
            | ``GeometricSlab703BT-Medium`` = 360
            | ``GeometricSlab703BT-MediumCond`` = 361
            | ``GeometricSlab703BT-Mediumltalic`` = 362
            | ``Georgia`` = 363
            | ``Georgia-Bold`` = 364
            | ``Georgia-Boldltalic`` = 365
            | ``Georgia-Italic`` = 366
            | ``GFutoGoBI 01 Pro-Bold`` = 367
            | ``GGothicBBBPro-Medium`` = 368
            | ``GiddyupStd`` = 369
            | ``Gigi-Regular`` = 370
            | ``GillSansMT`` = 371
            | ``GillSansMT-Bold`` = 372
            | ``GillSansMT-Boldltalic`` = 373
            | ``GillSansMT-Condensed`` = 374
            | ``GillSansMT-ExtraCondensedBold`` = 375
            | ``GillSansMT-ltalic`` = 376
            | ``GillSans-UltraBold`` = 377
            | ``GillSans-UltraBoldCondensed`` = 378
            | ``GJun34Pro-Medium`` = 379
            | ``GJun501 Pro-Bold`` = 380
            | ``GKyokalCAPro-Light`` = 381
            | ``GKyokalCAPro-Medium`` = 382
            | ``GKyokalCAPro-Regular`` = 383
            | ``GloucesterMT-ExtraCondensed`` = 384
            | ``GMaruGoPro-B`` = 385
            | ``GMaruGoPro-DB`` = 386
            | ``GMaruGoPro-M`` = 387
            | ``Gotham-Black`` = 388
            | ``Gotham-Blackltalic`` = 389
            | ``Gotham-Bold`` = 390
            | ``Gotham-Boldltalic`` = 391
            | ``Gotham-Book`` = 392
            | ``Gotham-Bookltalic`` = 393
            | ``Gotham-Light`` = 394
            | ``Gotham-Lightltalic`` = 395
            | ``Gotham-Medium`` = 396
            | ``Gotham-Mediumltalic`` = 397
            | ``GothamRounded-Bold`` = 398
            | ``GothamRounded-Boldltalic`` = 399
            | ``GothamRounded-Book`` = 400
            | ``GothamRounded-Bookltalic`` = 401
            | ``GothamRounded-Light`` = 402
            | ``GothamRounded-Lightltalic`` = 403
            | ``GothamRounded-Medium`` = 404
            | ``GothamRounded-Mediumltalic`` = 405
            | ``Gotham-Thin`` = 406
            | ``Gotham-Thinltalic`` = 407
            | ``Gotham-Ultra`` = 408
            | ``Gotham-Ultraltalic`` = 409
            | ``Gotham-XLight`` = 410
            | ``Gotham-XLightltalic`` = 411
            | ``GothicBBBPr5-Medium`` = 412
            | ``GothicBBBPro-Medium`` = 413
            | ``GothicMB101Pr5-Bold`` = 414
            | ``GothicMB101Pr5-DeBold`` = 415
            | ``GothicMB101Pr5-Heavy`` = 416
            | ``GothicMB101Pr5-Light`` = 417
            | ``GothicMBI 01 Pr5-Medium`` = 418
            | ``GothicMBI 01 Pr5-Regular`` = 419
            | ``GothicMBI 01 Pr5-Ultra`` = 420
            | ``GothicMBI 01 Pro-Bold`` = 421
            | ``GothicMBI 01 Pro-DeBold`` = 422
            | ``GothicMBI 01 Pro-Heavy`` = 423
            | ``GothicMBI 01 Pro-Light`` = 424
            | ``GothicMBI 01 Pro-Medium`` = 425
            | ``GothicMBI 01 Pro-Regular`` = 426
            | ``GothicMBI 01 Pro-Ultra`` = 427
            | ``GoudyOldStyleT-Bold`` = 428
            | ``GoudyOldStyleT-ltalic`` = 429
            | ``GoudyOldStyleT-Regular`` = 430
            | ``GoudyStout`` = 431
            | ``GranatExtrabold`` = 432
            | ``GrecoStd-B`` = 433
            | ``GrecoStd-DB`` = 434
            | ``GrecoStd-M`` = 435
            | ``GRyuminPro-Bold`` = 436
            | ``GRyuminPro-Light`` = 437
            | ``GRyuminPro-Medium`` = 438
            | ``GRyuminPro-Regular`` = 439
            | ``GShinGoPro-Bold`` = 440
            | ``GShinGoPro-Light`` = 441
            | ``GShinGoPro-Medium`` = 442
            | ``GShinGoPro-Regular`` = 443
            | ``GShinMGoPro-Bold`` = 444
            | ``GShinMGoPro-Light`` = 445
            | ``GShinMGoPro-Medium`` = 446
            | ``GShinMGoPro-Regular`` = 447
            | ``Haettenschweiler`` = 448
            | ``HarlowSolid`` = 449
            | ``Harrington`` = 450
            | ``HarucraftStd-Heavy`` = 451
            | ``HaruGakuStd-Light`` = 452
            | ``HelveticaLTStd-Blk`` = 453
            | ``HelveticaLTStd-BlkCond`` = 454
            | ``HelveticaLTStd-BlkCondObl`` = 455
            | ``HelveticaLTStd-BlkObl`` = 456
            | ``HelveticaLTStd-Bold`` = 457
            | ``HelveticaLTStd-BoldCond`` = 458
            | ``HelveticaLTStd-BoldCondObl`` = 459
            | ``HelveticaLTStd-BoldObl`` = 460
            | ``HelveticaLTStd-Comp`` = 461
            | ``HelveticaLTStd-Cond`` = 462
            | ``Helvetica LTStd-CondObl`` = 463
            | ``HelveticaLTStd-ExtraComp`` = 464
            | ``HelveticaLTStd-Fractions`` = 465
            | ``HelveticaLTStd-FractionsBd`` = 466
            | ``HelveticaLTStd-Light`` = 467
            | ``HelveticaLTStd-LightCond`` = 468
            | ``HelveticaLTStd-LightCondObl`` = 469
            | ``HelveticaLTStd-LightObl`` = 470
            | ``HelveticaLTStd-Obl`` = 471
            | ``HelveticaLTStd-Roman`` = 472
            | ``HelveticaLTStd-UltraComp`` = 473
            | ``HelveticaNeueLTCom-Bd`` = 474
            | ``HelveticaNeueLTCom-BdCn`` = 475
            | ``HelveticaNeueLTCom-BdCnO`` = 476
            | ``HelveticaNeueLTCom-BdEx`` = 477
            | ``HelveticaNeueLTCom-BdExO`` = 478
            | ``HelveticaNeueLTCom-Bdlt`` = 479
            | ``HelveticaNeueLTCom-BdOu`` = 480
            | ``HelveticaNeueLTCom-Blk`` = 481
            | ``HelveticaNeueLTCom-BlkCn`` = 482
            | ``HelveticaNeueLTCom-BlkCnO`` = 483
            | ``HelveticaNeueLTCom-BlkEx`` = 484
            | ``HelveticaNeueLTCom-BlkExO`` = 485
            | ``HelveticaNeueLTCom-Blklt`` = 486
            | ``HelveticaNeueLTCom-Cn`` = 487
            | ``HelveticaNeueLTCom-CnO`` = 488
            | ``HelveticaNeueLTCom-Ex`` = 489
            | ``HelveticaNeueLTCom-ExO`` = 490
            | ``HelveticaNeueLTCom-Hv`` = 491
            | ``HelveticaNeueLTCom-HvCn`` = 492
            | ``HelveticaNeueLTCom-HvCnO`` = 493
            | ``HelveticaNeueLTCom-HvEx`` = 494
            | ``HelveticaNeueLTCom-HvExO`` = 495
            | ``HelveticaNeueLTCom-HvIt`` = 496
            | ``HelveticaNeueLTCom-lt`` = 497
            | ``HelveticaNeueLTCom-LtCn`` = 498
            | ``HelveticaNeueLTCom-LtCnO`` = 499
            | ``HelveticaNeueLTCom-LtEx`` = 500
            | ``HelveticaNeueLTCom-LtExO`` = 501
            | ``HelveticaNeueLTCom-Ltlt`` = 502
            | ``HelveticaNeueLTCom-Md`` = 503
            | ``HelveticaNeueLTCom-MdCn`` = 504
            | ``HelveticaNeueLTCom-MdCnO`` = 505
            | ``HelveticaNeueLTCom-MdEx`` = 506
            | ``HelveticaNeueLTCom-MdExO`` = 507
            | ``HelveticaNeueLTCom-Mdlt`` = 508
            | ``HelveticaNeueLT Com-Roman`` = 509
            | ``HelveticaNeueLT Com-Th`` = 510
            | ``HelveticaNeueLT Com-ThCn`` = 511
            | ``HelveticaNeueLT Com-ThCnO`` = 512
            | ``HelveticaNeueLTCom-ThEx`` = 513
            | ``HelveticaNeueLTCom-ThExO`` = 514
            | ``HelveticaNeueLT Com-Thlt`` = 515
            | ``HelveticaNeueLTCom-UltLt`` = 516
            | ``HelveticaNeueLTCom-UltLtCn`` = 517
            | ``HelveticaNeueLTCom-UltLtCnO`` = 518
            | ``HelveticaNeueLTCom-UltLtEx`` = 519
            | ``HelveticaNeueLT Com-UltLtExO`` = 520
            | ``HelveticaNeueLT Com-UltLtlt`` = 521
            | ``HelveticaNeueLTCom-XBlkCn`` = 522
            | ``HelveticaNeueLT Com-XBlkCnO`` = 523
            | ``HighlandGothicFLF-Bold`` = 524
            | ``H ighT owerT ext-ltalic`` = 525
            | ``HighTowerText-Reg`` = 526
            | ``HiraginoKaku-W9-90msp-RKSJ-H`` = 527
            | ``HiraginoKaku-W9-90ms-RKSJ-H`` = 528
            | ``HoboStd`` = 529
            | ``HoloLensMDL2Assets`` = 530
            | ``HoureiStd-EB`` = 531
            | ``Humanist521 BT-Bold`` = 532
            | ``Humanist521 BT-Boldltalic`` = 533
            | ``Humanist521 BT-ltalic`` = 534
            | ``Humanist521 BT-Liqht`` = 535
            | ``Humanist521 BT-Light`` = 536
            | ``Humanist521 BT-Lightltalic`` = 537
            | ``Humanist521 BT-Roman`` = 538
            | ``Humanist777BT-BlackB`` = 539
            | ``Humanist777BT-BlackCondensedB`` = 540
            | ``Humanist777BT-BoldCondensedB`` = 541
            | ``Humanist777BT-LightB`` = 542
            | ``Humanist777BT-RomanB`` = 543
            | ``Humanist777BT-RomanCondensedB`` = 544
            | ``HummingStd-B`` = 545
            | ``HummingStd-D`` = 546
            | ``HummingStd-E`` = 547
            | ``HummingStd-L`` = 548
            | ``HummingStd-M`` = 549
            | ``HYArialUnicodeMS-`` = 550
            | ``HYi4gj`` = 551
            | ``Impact`` = 552
            | ``ImprintMT-Shadow`` = 553
            | ``InformalRoman-Regular`` = 554
            | ``InkFree`` = 555
            | ``IntroWOI-BlackAlt`` = 556
            | ``ITCAvantGardeStd-Bk`` = 557
            | ``ITCAvantGardeStd-BkCn`` = 558
            | ``ITCAvantGardeStd-BkCnObl`` = 559
            | ``ITCAvantGardeStd-BkObl`` = 560
            | ``ITCAvantGardeStd-Bold`` = 561
            | ``ITCAvantGardeStd-BoldCn`` = 562
            | ``ITCAvantGardeStd-BoldCnObl`` = 563
            | ``ITCAvantGardeStd-BoldObl`` = 564
            | ``ITCAvantGardeStd-Demi`` = 565
            | ``ITCAvantGardeStd-DemiCn`` = 566
            | ``ITCAvantGardeStd-DemiCnObl`` = 567
            | ``ITCAvantGardeStd-DemiObl`` = 568
            | ``ITCAvantGardeStd-Md`` = 569
            | ``ITCAvantGardeStd-MdCn`` = 570
            | ``ITCAvantGardeStd-MdCnObl`` = 571
            | ``ITCAvantGardeStd-MdObl`` = 572
            | ``ITCAvantGardeStd-XLt`` = 573
            | ``ITCAvantGardeStd-XLtCn`` = 574
            | ``ITCAvantGardeStd-XLtCnObl`` = 575
            | ``ITCAvantGardeStd-XLtObl`` = 576
            | ``lwataNewGothicW55-U`` = 577
            | ``JavaneseText`` = 578
            | ``Jokerman-Regular`` = 579
            | ``JominStd-Light`` = 580
            | ``JuicelTC-Regular`` = 581
            | ``Jun101 Pro-Light`` = 582
            | ``Jun201 Pro-Regular`` = 583
            | ``Jun34Pro-Medium`` = 584
            | ``Jun501 Pro-Bold`` = 585
            | ``KaishoMCBKIPro-DeBold`` = 586
            | ``KaiTi`` = 587
            | ``KakuminPro-Bold`` = 588
            | ``KakuminPro-Heavy`` = 589
            | ``KakuminPro-Medium`` = 590
            | ``KakuminPro-Regular`` = 591
            | ``KakureiStd-EB`` = 592
            | ``KakureiStd-L`` = 593
            | ``KakureiStd-M`` = 594
            | ``KanteiryuStd-Ultra`` = 595
            | ``KaufmannBT-Regular`` = 596
            | ``KleePro-DB`` = 597
            | ``KleePro-M`` = 598
            | ``KochoStd-Heavy`` = 599
            | ``KokinEdoStd-EB`` = 600
            | ``KokinHigeStd-EB`` = 601
            | ``Konnect-ExtraBold`` = 602
            | ``KozGoPr6N-Bold`` = 603
            | ``KozGoPr6N-ExtraLight`` = 604
            | ``KozGoPr6N-Heavy`` = 605
            | ``KozGoPr6N-Light`` = 606
            | ``KozGoPr6N-Medium`` = 607
            | ``KozGoPr6N-Reqular`` = 608
            | ``KozGoPro-Bold`` = 609
            | ``KozGoPro-ExtraLight`` = 610
            | ``KozGoPro-Heavy`` = 611
            | ``KozGoPro-Light`` = 612
            | ``KozGoPro-Medium`` = 613
            | ``KozGoPro-Regular`` = 614
            | ``KozMinPr6N-Bold`` = 615
            | ``KozMinPr6N-ExtraLight`` = 616
            | ``KozMinPr6N-Heavy`` = 617
            | ``KozMinPr6N-Light`` = 618
            | ``KozMinPr6N-Medium`` = 619
            | ``KozMinPr6N-Regular`` = 620
            | ``KozMinPro-Bold`` = 621
            | ``KozMinPro-ExtraLight`` = 622
            | ``KozM in Pro-Heavy`` = 623
            | ``KozMinPro-Light`` = 624
            | ``KozMinPro-Medium`` = 625
            | ``KozMinPro-Regular`` = 626
            | ``KristenITC-Regular`` = 627
            | ``KumoyaStd-Regular`` = 628
            | ``KunstlerScript`` = 629
            | ``KurokaneStd-EB`` = 630
            | ``KyokalCAPro-Light`` = 631
            | ``KyokalCAPro-Medium`` = 632
            | ``KyokalCAPro-Regular`` = 633
            | ``LatinWide`` = 634
            | ``Leelawadee`` = 635
            | ``Leelawadee-Bold`` = 636
            | ``LeelawadeeUI`` = 637
            | ``LeelawadeeUI-Bold`` = 638
            | ``LeelawadeeLM-Semilight`` = 639
            | ``LetterGothicStd`` = 640
            | ``LetterGothicStd-Bold`` = 641
            | ``LetterGothicStd-BoldSlanted`` = 642
            | ``LetterGothicStd-Slanted`` = 643
            | ``LiHeiPro`` = 644
            | ``LikureiStd-RequIar`` = 645
            | ``LiSu`` = 646
            | ``LithosPro-Black`` = 647
            | ``LithosPro-Regular`` = 648
            | ``Lolita`` = 649
            | ``LucidaBright`` = 650
            | ``LucidaBright-Demi`` = 651
            | ``LucidaBright-Demiltalic`` = 652
            | ``LucidaBright-ltalic`` = 653
            | ``LucidaCalligraphy-ltalic`` = 654
            | ``LucidaConsole`` = 655
            | ``LucidaFax`` = 656
            | ``LucidaFax-Demi`` = 657
            | ``LucidaFax-Demiltalic`` = 658
            | ``LucidaFax-ltalic`` = 659
            | ``LucidaHandwriting-ltalic`` = 660
            | ``LucidaSans`` = 661
            | ``LucidaSans-Demi`` = 662
            | ``LucidaSans-Demiltalic`` = 663
            | ``LucidaSans-ltalic`` = 664
            | ``LucidaSansStd`` = 665
            | ``LucidaSansStd-Bold`` = 666
            | ``LucidaSansStd-Boldltalic`` = 667
            | ``LucidaSansStd-ltalic`` = 668
            | ``LucidaSans-Typewriter`` = 669
            | ``LucidaSans-TypewriterBold`` = 670
            | ``LucidaSans-TypewriterBoldOblique`` = 671
            | ``LucidaSans-TypewriterOblique`` = 672
            | ``LucidaSansUnicode`` = 673
            | ``LyraStd-DB`` = 674
            | ``MacaroniStd-DB`` = 675
            | ``Magneto-Bold`` = 676
            | ``MaiandraGD-Regular`` = 677
            | ``MalgunGothic`` = 678
            | ``MalgunGothicBold`` = 679
            | ``MalgunGothic-Semilight`` = 680
            | ``ManyoGyoshoStd-E`` = 681
            | ``ManyoKoinLarqeStd-B`` = 682
            | ``ManyoKoinStd-B`` = 683
            | ``ManyoSoshoStd-E`` = 684
            | ``Marlett`` = 685
            | ``MaruFoPro-Bold`` = 686
            | ``MaruFoPro-Heavy`` = 687
            | ``MaruFoPro-Medium`` = 688
            | ``MaruFoPro-Regular`` = 689
            | ``MatisseElegantoPro-B`` = 690
            | ``MatisseElegantoPro-DB`` = 691
            | ``MatisseElegantoPro-EB`` = 692
            | ``MatisseElegantoPro-M`` = 693
            | ``MatisseElegantoPro-UB`` = 694
            | ``MatisseHatsuhiPro-B`` = 695
            | ``MatisseHatsuhiPro-DB`` = 696
            | ``MatisseHatsuhiPro-EB`` = 697
            | ``MatisseHatsuhiPro-M`` = 698
            | ``MatisseMinoriPro-B`` = 699
            | ``MatisseMinoriPro-DB`` = 700
            | ``MatisseMinoriPro-EB`` = 701
            | ``MatisseMinoriPro-M`` = 702
            | ``MatissePro-B`` = 703
            | ``MatissePro-DB`` = 704
            | ``MatissePro-EB`` = 705
            | ``MatissePro-L`` = 706
            | ``MatissePro-M`` = 707
            | ``MatisseProN-B`` = 708
            | ``MatisseProN-DB`` = 709
            | ``MatisseProN-EB`` = 710
            | ``MatisseProN-L`` = 711
            | ``MatisseProN-M`` = 712
            | ``MatisseProN-UB`` = 713
            | ``MatissePro-UB`` = 714
            | ``MatisseVPro-B`` = 715
            | ``MatisseVPro-DB`` = 716
            | ``MatisseVPro-EB`` = 717
            | ``MatisseVPro-L`` = 718
            | ``MatisseVPro-M`` = 719
            | ``MatisseVPro-UB`` = 720
            | ``MatisseWakabaPro-B`` = 721
            | ``MatisseWakabaPro-DB`` = 722
            | ``MatisseWakabaPro-EB`` = 723
            | ``MatisseWakabaPro-M`` = 724
            | ``MaturaMTScriptCapitals`` = 725
            | ``Meiryo`` = 726
            | ``Meiryo-ltalic`` = 727
            | ``MesquiteStd`` = 728
            | ``MicrosoftHimalaya`` = 729
            | ``MicrosoftJhengHeiBold`` = 730
            | ``MicrosoftJhengHeiLight`` = 731
            | ``MicrosoftJhengHeiRegular`` = 732
            | ``MicrosoftJhengHeiUlBold`` = 733
            | ``MicrosoftJhengHeiUlLight`` = 734
            | ``MicrosoftJhengHeiUlRegular`` = 735
            | ``MicrosoftNewTaiLue`` = 736
            | ``MicrosoftNewTaiLue-Bold`` = 737
            | ``MicrosoftPhagsPa`` = 738
            | ``MicrosoftPhagsPa-Bold`` = 739
            | ``MicrosoftSansSerif`` = 740
            | ``MicrosoftTaiLe`` = 741
            | ``MicrosoftTaiLe-Bold`` = 742
            | ``MicrosoftUighur`` = 743
            | ``MicrosoftUighur-Bold`` = 744
            | ``MicrosoftYaHei`` = 745
            | ``MicrosoftYaHei-Bold`` = 746
            | ``MicrosoftYaHeiLight`` = 747
            | ``MicrosoftYaHeiUI`` = 748
            | ``MicrosoftYaHeiUl-Bold`` = 749
            | ``MicrosoftYaHeiUlLight`` = 750
            | ``Microsoft-Yi-Baiti`` = 751
            | ``MidashiGoPr5-MB31`` = 752
            | ``MidashiGoPro-MB31`` = 753
            | ``MidashiMinPr5-MA31`` = 754
            | ``MidashiMinPro-MA31`` = 755
            | ``MingLiU-ExtB`` = 756
            | ``Ming-Lt-HKSCS-ExtB`` = 757
            | ``MinionPro-Bold`` = 758
            | ``MinionPro-BoldCn`` = 759
            | ``MinionPro-BoldCnlt`` = 760
            | ``MinionPro-Boldlt`` = 761
            | ``MinionPro-lt`` = 762
            | ``MinionPro-Medium`` = 763
            | ``MinionPro-Mediumlt`` = 764
            | ``MinionPro-Regular`` = 765
            | ``MinionPro-Semibold`` = 766
            | ``MinionPro-Semiboldlt`` = 767
            | ``Mistral`` = 768
            | ``MNewsGPro-Light`` = 769
            | ``MNewsMPro-Light`` = 770
            | ``ModeMinAStd-B`` = 771
            | ``ModeMinBStd-B`` = 772
            | ``Modern-Regular`` = 773
            | ``MonFuturisExtra`` = 774
            | ``MongolianBaiti`` = 775
            | ``monoMMM5-Regular`` = 776
            | ``M onotypeCorsiva`` = 777
            | ``Mont-DEMOHeavy`` = 778
            | ``MS-Gothic`` = 779
            | ``MSOutlook`` = 780
            | ``MS-PGothic`` = 781
            | ``MSReferenceSansSerif`` = 782
            | ``MSReferenceSpecialty`` = 783
            | ``MS-UIGothic`` = 784
            | ``MusashiStd-Regular`` = 785
            | ``MVBoli`` = 786
            | ``MyanmarText`` = 787
            | ``MyanmarT ext-Bold`` = 788
            | ``MyriadArabic-Bold`` = 789
            | ``MyriadArabic-Boldlt`` = 790
            | ``MyriadArabic-lt`` = 791
            | ``MyriadArabic-Regular`` = 792
            | ``MyriadHebrew-Bold`` = 793
            | ``MyriadHebrew-Boldlt`` = 794
            | ``MyriadHebrew-lt`` = 795
            | ``MyriadHebrew-Regular`` = 796
            | ``MyriadPro-Black`` = 797
            | ``MyriadPro-BlackCond`` = 798
            | ``MyriadPro-BlackCondlt`` = 799
            | ``MyriadPro-Blacklt`` = 800
            | ``MyriadPro-BlackSemiCn`` = 801
            | ``MyriadPro-BlackSemiCnlt`` = 802
            | ``MyriadPro-BlackSemiExt`` = 803
            | ``MyriadPro-BlackSemiExtlt`` = 804
            | ``MyriadPro-Bold`` = 805
            | ``MyriadPro-BoldCond`` = 806
            | ``MyriadPro-BoldCondlt`` = 807
            | ``MyriadPro-Boldlt`` = 808
            | ``MyriadPro-BoldSemiCn`` = 809
            | ``MyriadPro-BoldSemiCnlt`` = 810
            | ``MyriadPro-BoldSemiExt`` = 811
            | ``MyriadPro-BoldSemiExtlt`` = 812
            | ``MyriadPro-Cond`` = 813
            | ``MyriadPro-Condlt`` = 814
            | ``MyriadPro-lt`` = 815
            | ``MyriadPro-Light`` = 816
            | ``MyriadPro-LightCond`` = 817
            | ``MyriadPro-LightCondlt`` = 818
            | ``MyriadPro-Lightlt`` = 819
            | ``MyriadPro-LightSemiCn`` = 820
            | ``MyriadPro-LightSemiCnlt`` = 821
            | ``MyriadPro-LightSemiExt`` = 822
            | ``MyriadPro-LightSemiExtlt`` = 823
            | ``MyriadPro-Regular`` = 824
            | ``MyriadPro-Semibold`` = 825
            | ``MyriadPro-SemiboldCond`` = 826
            | ``MyriadPro-SemiboldCondlt`` = 827
            | ``MyriadPro-Semiboldlt`` = 828
            | ``MyriadPro-SemiboldSemiCn`` = 829
            | ``MyriadPro-SemiboldSemiCnlt`` = 830
            | ``MyriadPro-SemiboldSemiExt`` = 831
            | ``MyriadPro-SemiboldSemiExtlt`` = 832
            | ``MyriadPro-SemiCn`` = 833
            | ``MyriadPro-SemiCnlt`` = 834
            | ``MyriadPro-SemiExt`` = 835
            | ``MyriadPro-SemiExtlt`` = 836
            | ``MysteryStd-DB`` = 837
            | ``NachinStd-Regular`` = 838
            | ``New`` = 839
            | ``NewCezannePro-B`` = 840
            | ``NewCezannePro-DB`` = 841
            | ``NewCezannePro-EB`` = 842
            | ``NewCezannePro-M`` = 843
            | ``NewCezanneProN-B`` = 844
            | ``NewCezanneProN-DB`` = 845
            | ``NewCezanneProN-EB`` = 846
            | ``NewCezanneProN-M`` = 847
            | ``NewCinemaAStd-D`` = 848
            | ``NewCinemaBStd-D`` = 849
            | ``NewGroteskSquareFOUR-Medium`` = 850
            | ``NewRodinPro-B`` = 851
            | ``NewRodinPro-DB`` = 852
            | ``NewRodinPro-EB`` = 853
            | ``NewRodinPro-L`` = 854
            | ``NewRodinPro-M`` = 855
            | ``NewRodinProN-B`` = 856
            | ``NewRodinProN-DB`` = 857
            | ``NewRodinProN-EB`` = 858
            | ``NewRodinProN-L`` = 859
            | ``NewRodinProN-M`` = 860
            | ``NewRodinProN-UB`` = 861
            | ``NewRodinPro-UB`` = 862
            | ``News701 BT-BoldA`` = 863
            | ``News701BT-ltalicA`` = 864
            | ``News706BT-BoldC`` = 865
            | ``NewsGothicBT-Bold`` = 866
            | ``NewsGothicBT-Boldltalic`` = 867
            | ``NewsGothicBT-Italic`` = 868
            | ``NewsGothicBT-Light`` = 869
            | ``NewsGothicBT-Roman`` = 870
            | ``NewsGothicBT-RomanCondensed`` = 871
            | ``NewsGothicMT`` = 872
            | ``NewsGothicMT-Bold`` = 873
            | ``NiagaraEngraved-Reg`` = 874
            | ``NiagaraSolid-Reg`` = 875
            | ``NimbusMono-Bol`` = 876
            | ``NimbusSanNov-Bol`` = 877
            | ``NimbusSanNovD-Ligh`` = 878
            | ``NimbusSanNovT-SemiBoldCond`` = 879
            | ``NirmalaUI`` = 880
            | ``NirmalaUI-Bold`` = 881
            | ``NirmalaLM-Semilight`` = 882
            | ``NotoSansHans-Black`` = 883
            | ``NotoSansHans-Bold`` = 884
            | ``NotoSansHans-DemiLight`` = 885
            | ``NotoSansHans-Light`` = 886
            | ``NotoSansHans-Medium`` = 887
            | ``NotoSansHans-Regular`` = 888
            | ``NotoSansHans-Thin`` = 889
            | ``NSimSun`` = 890
            | ``NuevaStd-Bold`` = 891
            | ``NuevaStd-BoldCond`` = 892
            | ``NuevaStd-BoldCondltalic`` = 893
            | ``NuevaStd-Cond`` = 894
            | ``NuevaStd-Condltalic`` = 895
            | ``NuevaStd-ltalic`` = 896
            | ``NutmegHeadline-Black`` = 897
            | ``OCRAbyBT-Regular`` = 898
            | ``OCRA Extended`` = 899
            | ``OCRAStd`` = 900
            | ``OCRBIOPitchBT-Regular`` = 901
            | ``OCR-B-Seagull`` = 902
            | ``OedKtrStd-E`` = 903
            | ``ok.LeagueGothic-`` = 904
            | ``OldEnglishTextMT`` = 905
            | ``Onyx`` = 906
            | ``OratorStd`` = 907
            | ``OratorStd-Slanted`` = 908
            | ``OutaiKaiStd-Light`` = 909
            | ``PalaceScriptMT`` = 910
            | ``PalatinoLinotype-Bold`` = 911
            | ``PalatinoLinotype-Boldltalic`` = 912
            | ``PalatinoLinotype-ltalic`` = 913
            | ``PalatinoLinotype-Roman`` = 914
            | ``Panton-Bold`` = 915
            | ``Panton-Regular`` = 916
            | ``Papyrus-Regular`` = 917
            | ``Parchment-Regular`` = 918
            | ``PareWideBoldltalic`` = 919
            | ``Perpetua`` = 920
            | ``Perpetua-Bold`` = 921
            | ``Perpetua-Boldltalic`` = 922
            | ``Perpetua-ltalic`` = 923
            | ``PerpetuaTitlingMT-Bold`` = 924
            | ``PerpetuaTitlingMT-Light`` = 925
            | ``PFDinTextCompPro-Medium`` = 926
            | ``Pfuk`` = 927
            | ``PING1.2-`` = 928
            | ``Playbill`` = 929
            | ``PMingLiU-ExtB`` = 930
            | ``PoorRichard-Regular`` = 931
            | ``PopFuryStd-B`` = 932
            | ``PopHappinessStd-EB`` = 933
            | ``PopJoyStd-B`` = 934
            | ``PoplarStd`` = 935
            | ``PreMomoStd-Bold`` = 936
            | ``PrestigeEliteStd-Bd`` = 937
            | ``Pristina-Regular`` = 938
            | ``Progesterone`` = 939
            | ``Rageltalic`` = 940
            | ``RaglanStd-UB`` = 941
            | ``RailwayStd-B`` = 942
            | ``Raleigh-DemiBold`` = 943
            | ``RampartStd-EB`` = 944
            | ``RampartTLStd-EB`` = 945
            | ``Ravie`` = 946
            | ``RegencieLight`` = 947
            | ``RegencieLightAlt`` = 948
            | ``RegencieLightAltObl`` = 949
            | ``RegencieLightObl`` = 950
            | ``ReggaeStd-B`` = 951
            | ``Reishol 01 Std-Medium`` = 952
            | ``RocknRollStd-DB`` = 953
            | ``Rockwell`` = 954
            | ``Rockwell-Bold`` = 955
            | ``Rockwell-Boldltalic`` = 956
            | ``Rockwell-Condensed`` = 957
            | ``Rockwell-CondensedBold`` = 958
            | ``Rockwell-ExtraBold`` = 959
            | ``RockweN-ltalic`` = 960
            | ``RodinBokutohPro-B`` = 961
            | ``RodinBokutohPro-DB`` = 962
            | ``RodinBokutohPro-EB`` = 963
            | ``RodinBokutohPro-L`` = 964
            | ``RodinBokutohPro-M`` = 965
            | ``RodinBokutohPro-UB`` = 966
            | ``RodinCamillePro-B`` = 967
            | ``RodinCamillePro-DB`` = 968
            | ``RodinCamillePro-EB`` = 969
            | ``RodinCattleyaPro-B`` = 970
            | ``RodinCattleyaPro-DB`` = 971
            | ``RodinCattleyaPro-EB`` = 972
            | ``RodinCattleyaPro-L`` = 973
            | ``RodinCattleyaPro-M`` = 974
            | ``RodinCattleyaPro-UB`` = 975
            | ``RodinHappyPro-B`` = 976
            | ``RodinHappyPro-DB`` = 977
            | ``RodinHappyPro-EB`` = 978
            | ``RodinHappyPro-L`` = 979
            | ``RodinHappyPro-M`` = 980
            | ``RodinHappyPro-UB`` = 981
            | ``RodinHimawariPro-B`` = 982
            | ``RodinHimawariPro-DB`` = 983
            | ``RodinHimawariPro-EB`` = 984
            | ``RodinHimawariPro-L`` = 985
            | ``RodinHimawariPro-M`` = 986
            | ``RodinHimawariPro-UB`` = 987
            | ``RodinMariaPro-B`` = 988
            | ``RodinMariaPro-DB`` = 989
            | ``RodinMariaPro-EB`` = 990
            | ``RodinNTLGPro-B`` = 991
            | ``RodinNTLGPro-DB`` = 992
            | ``RodinNTLGPro-EB`` = 993
            | ``RodinNTLGPro-L`` = 994
            | ``RodinNTLGPro-M`` = 995
            | ``RodinNTLGPro-UB`` = 996
            | ``RodinPro-B`` = 997
            | ``RodinPro-DB`` = 998
            | ``RodinPro-EB`` = 999
            | ``RodinPro-L`` = 1000
            | ``RodinPro-M`` = 1001
            | ``RodinProN-B`` = 1002
            | ``RodinProN-DB`` = 1003
            | ``RodinProN-EB`` = 1004
            | ``RodinProN-L`` = 1005
            | ``RodinProN-M`` = 1006
            | ``RodinProN-UB`` = 1007
            | ``RodinPro-UB`` = 1008
            | ``RodinRosePro-B`` = 1009
            | ``RodinRosePro-DB`` = 1010
            | ``RodinRosePro-EB`` = 1011
            | ``RodinWanpakuPro-B`` = 1012
            | ``RodinWanpakuPro-DB`` = 1013
            | ``RodinWanpakuPro-EB`` = 1014
            | ``RodinWanpakuPro-L`` = 1015
            | ``RodinWanpakuPro-M`` = 1016
            | ``RodinWanpakuPro-UB`` = 1017
            | ``RosewoodStd-Regular`` = 1018
            | ``RowdyStd-EB`` = 1019
            | ``RyuminPr5-Bold`` = 1020
            | ``RyuminPr5-ExBold`` = 1021
            | ``RyuminPr5-ExHeavy`` = 1022
            | ``RyuminPr5-Heavy`` = 1023
            | ``RyuminPr5-Light`` = 1024
            | ``RyuminPr5-Medium`` = 1025
            | ``RyuminPr5-Regular`` = 1026
            | ``RyuminPr5-Ultra`` = 1027
            | ``RyuminPro-Bold`` = 1028
            | ``RyuminPro-ExBold`` = 1029
            | ``RyuminPro-ExHeavy`` = 1030
            | ``RyuminPro-Heavy`` = 1031
            | ``RyuminPro-Light`` = 1032
            | ``RyuminPro-Medium`` = 1033
            | ``RyuminPro-Regular`` = 1034
            | ``RyuminPro-Ultra`` = 1035
            | ``SchadowBT-Bold`` = 1036
            | ``SchadowBT-Roman`` = 1037
            | ``ScriptMTBold`` = 1038
            | ``Seagull:MedicalDevicesv1.0`` = 1039
            | ``SeagullADRvIO`` = 1040
            | ``SeagullElectricalvl 0`` = 1041
            | ``SeagullEmergencyvl 0`` = 1042
            | ``SeagullGHSvIO`` = 1043
            | ``SeagullHazardvIO`` = 1044
            | ``SeagullLogosvIO`` = 1045
            | ``SeagullPackagingvl 0`` = 1046
            | ``SeagullPaintvIO`` = 1047
            | ``SeagullRecyclingvl 0`` = 1048
            | ``SeagullRiskPhrasesvl 0`` = 1049
            | ``SeagullTextileCarevI 0`` = 1050
            | ``SeagullWarningvl 0`` = 1051
            | ``SegoeM DL2Assets`` = 1052
            | ``SegoePrint`` = 1053
            | ``SegoePrint-Bold`` = 1054
            | ``SegoeScript`` = 1055
            | ``SegoeScript-Bold`` = 1056
            | ``SegoeUI`` = 1057
            | ``SegoeUIBlack`` = 1058
            | ``SegoeUIBlack-ltalic`` = 1059
            | ``SegoeUI-Bold`` = 1060
            | ``SegoeUI-Boldltalic`` = 1061
            | ``SegoeUIEmoji`` = 1062
            | ``SegoeLIIHistoric`` = 1063
            | ``SegoeUI-ltalic`` = 1064
            | ``SegoeLM-Light`` = 1065
            | ``SegoeUI-Lightltalic`` = 1066
            | ``SegoeUI-Semibold`` = 1067
            | ``SegoeUI-Semiboldltalic`` = 1068
            | ``SegoeUI-Semilight`` = 1069
            | ``SegoeUI-Semilightltalic`` = 1070
            | ``SegoeUISymbol`` = 1071
            | ``SeiKaiCBI Std-Regular`` = 1072
            | ``SeuratCapiePro-B`` = 1073
            | ``SeuratCapiePro-DB`` = 1074
            | ``SeuratCapiePro-EB`` = 1075
            | ``SeuratCapiePro-M`` = 1076
            | ``SeuratPro-B`` = 1077
            | ``SeuratPro-DB`` = 1078
            | ``SeuratPro-EB`` = 1079
            | ``SeuratPro-L`` = 1080
            | ``SeuratPro-M`` = 1081
            | ``SeuratProN-B`` = 1082
            | ``SeuratProN-DB`` = 1083
            | ``SeuratProN-EB`` = 1084
            | ``SeuratProN-L`` = 1085
            | ``SeuratProN-M`` = 1086
            | ``SeuratProN-UB`` = 1087
            | ``SeuratPro-UB`` = 1088
            | ``ShadowStd-B`` = 1089
            | ``ShadowTLStd-B`` = 1090
            | ``ShinGoMin-Emboss`` = 1091
            | ``ShinGoMin-Futoline`` = 1092
            | ``ShinGoMin-Shadow`` = 1093
            | ``ShinGoPr5-Bold`` = 1094
            | ``ShinGoPr5-DeBold`` = 1095
            | ``ShinGoPr5-ExLight`` = 1096
            | ``ShinGoPr5-Heavy`` = 1097
            | ``ShinGoPr5-Light`` = 1098
            | ``ShinGoPr5-Medium`` = 1099
            | ``ShinGoPr5-Regular`` = 1100
            | ``ShinGoPr5-Ultra`` = 1101
            | ``ShinGoPr6-Bold`` = 1102
            | ``ShinGoPr6-DeBold`` = 1103
            | ``ShinGoPr6-ExLight`` = 1104
            | ``ShinGoPr6-Heavy`` = 1105
            | ``ShinGoPr6-Light`` = 1106
            | ``ShinGoPr6-Medium`` = 1107
            | ``ShinGoPr6N-Bold`` = 1108
            | ``ShinGoPr6N-DeBold`` = 1109
            | ``ShinGoPr6N-ExLight`` = 1110
            | ``ShinGoPr6N-Heavy`` = 1111
            | ``ShinGoPr6N-Liqht`` = 1112
            | ``ShinGoPr6N-Medium`` = 1113
            | ``ShinGoPr6N-Regular`` = 1114
            | ``ShinGoPr6N-Ultra`` = 1115
            | ``ShinGoPr6-Regular`` = 1116
            | ``ShinGoPr6-Ultra`` = 1117
            | ``ShinGoPro-Bold`` = 1118
            | ``ShinGoPro-DeBold`` = 1119
            | ``ShinGoPro-ExLight`` = 1120
            | ``ShinGoPro-Heavy`` = 1121
            | ``ShinGoPro-Light`` = 1122
            | ``ShinGoPro-Medium`` = 1123
            | ``ShinGoPro-Regular`` = 1124
            | ``ShinGoPro-Ultra`` = 1125
            | ``ShinMGoPro-Bold`` = 1126
            | ``ShinMGoPro-DeBold`` = 1127
            | ``ShinMGoPro-Heavy`` = 1128
            | ``ShinMGoPro-Light`` = 1129
            | ``ShinMGoPro-Medium`` = 1130
            | ``ShinMGoPro-Regular`` = 1131
            | ``ShinMGoPro-Ultra`` = 1132
            | ``ShinseiKaiPro-CBSK1`` = 1133
            | ``ShowcardGothic-Reg`` = 1134
            | ``Silka-Black`` = 1135
            | ``SimHei`` = 1136
            | ``SimpMusicBasePSMT`` = 1137
            | ``SimSun`` = 1138
            | ``SimSun-ExtB`` = 1139
            | ``SitkaBanner`` = 1140
            | ``SitkaBanner-Bold`` = 1141
            | ``SitkaBanner-Boldltalic`` = 1142
            | ``SitkaBanner-ltalic`` = 1143
            | ``SitkaDisplay`` = 1144
            | ``SitkaDisplay-Bold`` = 1145
            | ``SitkaDisplay-Boldltalic`` = 1146
            | ``SitkaDisplay-ltalic`` = 1147
            | ``SitkaHeading`` = 1148
            | ``SitkaHeading-Bold`` = 1149
            | ``SitkaHeadinq-Boldltalic`` = 1150
            | ``SitkaHeading-ltalic`` = 1151
            | ``SitkaSmall`` = 1152
            | ``SitkaSmall-Bold`` = 1153
            | ``SitkaSmall-Boldltalic`` = 1154
            | ``SitkaSmall-ltalic`` = 1155
            | ``SitkaSubheading`` = 1156
            | ``SitkaSubheading-Bold`` = 1157
            | ``SitkaSubheading-Boldltalic`` = 1158
            | ``SitkaSubheading-ltalic`` = 1159
            | ``SitkaText`` = 1160
            | ``SitkaText-Bold`` = 1161
            | ``SitkaT ext-Boldltalic`` = 1162
            | ``SitkaText-ltalic`` = 1163
            | ``SkipStd-B`` = 1164
            | ``SlumpStd-DB`` = 1165
            | ``SnapITC-Regular`` = 1166
            | ``SPLetterFig-BoldOblique`` = 1167
            | ``Square721BT-Bold`` = 1168
            | ``Square721 BT-BoldCondensed`` = 1169
            | ``Square721 BT-Roman`` = 1170
            | ``Square721 BT-RomanCondensed`` = 1171
            | ``StagSansRound-Semibold`` = 1172
            | ``STCaiyun`` = 1173
            | ``SteelworkStd-B`` = 1174
            | ``Stencil`` = 1175
            | ``StencilStd`` = 1176
            | ``STFangsong`` = 1177
            | ``STHupo`` = 1178
            | ``StickStd-B`` = 1179
            | ``STKaiti`` = 1180
            | ``STLiti`` = 1181
            | ``StoneSanslllTCPro-Bd`` = 1182
            | ``StoneSanslllTCPro-Md`` = 1183
            | ``StoneSanslllTCPro-SmBd`` = 1184
            | ``STSong`` = 1185
            | ``STXihei`` = 1186
            | ``STXingkai`` = 1187
            | ``STXinwei`` = 1188
            | ``STZhongsong`` = 1189
            | ``sucaijishikufangti`` = 1190
            | ``Swiss721BT-Black`` = 1191
            | ``Swiss721 BT-BlackCondensed`` = 1192
            | ``Swiss721BT-Bold`` = 1193
            | ``Swiss721 BT-BoldCondensed`` = 1194
            | ``Swiss721 BT-BoldCondensedltalic`` = 1195
            | ``Swiss721BT-Boldltalic`` = 1196
            | ``Swiss721 BT-Heavy`` = 1197
            | ``Swiss721BT-ltalic`` = 1198
            | ``Swiss721 BT-ltalicCondensed`` = 1199
            | ``Swiss721BT-Light`` = 1200
            | ``Swiss721 BT-LightExtended`` = 1201
            | ``Swiss721 BT-Lightltalic`` = 1202
            | ``Swiss721 BT-Roman`` = 1203
            | ``Swiss721 BT-RomanCondensed`` = 1204
            | ``Sylfaen`` = 1205
            | ``Symbol`` = 1206
            | ``SymbolMT`` = 1207
            | ``Tahoma`` = 1208
            | ``Tahoma-Bold`` = 1209
            | ``TakaHandStd-Bold`` = 1210
            | ``TakaHandStd-DeBold`` = 1211
            | ``TakaHandStd-Heavy`` = 1212
            | ``TakaHandStd-Light`` = 1213
            | ``TakaHandStd-Medium`` = 1214
            | ``TechnoRegular`` = 1215
            | ``TektonPro-Bold`` = 1216
            | ``T ektonPro-BoldCond`` = 1217
            | ``TektonPro-BoldExt`` = 1218
            | ``T ektonPro-BoldObl`` = 1219
            | ``TempusSansITC`` = 1220
            | ``Texta-Regular`` = 1221
            | ``TimesNewRomanPS-BoldltalicMT`` = 1222
            | ``TimesNewRomanPS-BoldMT`` = 1223
            | ``TimesNewRomanPS-ltalicMT`` = 1224
            | ``TimesNewRomanPSMT`` = 1225
            | ``TiresiasPCfontZ`` = 1226
            | ``TrajanPro-Bold`` = 1227
            | ``TrajanPro-Regular`` = 1228
            | ``T rebuchet-Boldltalic`` = 1229
            | ``TrebuchetMS`` = 1230
            | ``TrebuchetMS-Bold`` = 1231
            | ``TrebuchetMS-ltalic`` = 1232
            | ``Trenda-Heavy`` = 1233
            | ``Trenda-Regular`` = 1234
            | ``TsukuAMDMinStd-E`` = 1235
            | ``TsukuARdGothicStd-B`` = 1236
            | ``TsukuARdGothicStd-D`` = 1237
            | ``TsukuARdGothicStd-E`` = 1238
            | ``TsukuARdGothicStd-L`` = 1239
            | ``TsukuARdGothicStd-M`` = 1240
            | ``TsukuARdGothicStd-R`` = 1241
            | ``TsukuBMDMinStd-E`` = 1242
            | ``TsukuBRdGothicStd-B`` = 1243
            | ``TsukuGoPr5-D`` = 1244
            | ``TsukuGoPr5-L`` = 1245
            | ``TsukuGoPr5-M`` = 1246
            | ``TsukuGoPr5N-D`` = 1247
            | ``TsukuGoPr5N-L`` = 1248
            | ``TsukuGoPr5N-M`` = 1249
            | ``TsukuGoPr5N-R`` = 1250
            | ``TsukuGoPr5-R`` = 1251
            | ``TsukuGoPro-B`` = 1252
            | ``TsukuGoPro-D`` = 1253
            | ``TsukuGoPro-E`` = 1254
            | ``TsukuGoPro-H`` = 1255
            | ``TsukuGoPro-L`` = 1256
            | ``TsukuGoPro-M`` = 1257
            | ``TsukuGoPro-R`` = 1258
            | ``TsukuGoPro-U`` = 1259
            | ``TsukuMinPr5-B`` = 1260
            | ``TsukuMinPr5-D`` = 1261
            | ``TsukuMinPr5-E`` = 1262
            | ``TsukuMinPr5-HV`` = 1263
            | ``TsukuMinPr5-L`` = 1264
            | ``TsukuMinPr5-LB`` = 1265
            | ``TsukuMinPr5-M`` = 1266
            | ``TsukuMinPr5N-D`` = 1267
            | ``TsukuMinPr5N-E`` = 1268
            | ``TsukuMinPr5N-HV`` = 1269
            | ``TsukuMinPr5N-L`` = 1270
            | ``TsukuMinPr5N-LB`` = 1271
            | ``TsukuMinPr5N-M`` = 1272
            | ``TsukuMinPr5N-R`` = 1273
            | ``TsukuMinPr5N-RB`` = 1274
            | ``TsukuMinPr5-R`` = 1275
            | ``TsukuMinPr5-RB`` = 1276
            | ``TsukuMinPro-B`` = 1277
            | ``TsukuMinPro-D`` = 1278
            | ``TsukuMinPro-E`` = 1279
            | ``TsukuMinPro-HV`` = 1280
            | ``TsukuMinPro-L`` = 1281
            | ``TsukuMinPro-LB`` = 1282
            | ``TsukuMinPro-M`` = 1283
            | ``TsukuMinPro-R`` = 1284
            | ``TsukuMinPro-RB`` = 1285
            | ``TsukuOldMinPro-R`` = 1286
            | ``TwCenMT-Bold`` = 1287
            | ``TwCenMT-Boldltalic`` = 1288
            | ``TwCenMT-Condensed`` = 1289
            | ``TwCenMT-CondensedBold`` = 1290
            | ``TwCenMT-CondensedExtraBold`` = 1291
            | ``TwCenMT-ltalic`` = 1292
            | ``TwCenMT-Regular`` = 1293
            | ``TypoUprightBT-Regular`` = 1294
            | ``UDReiminPr6N-ExBold`` = 1295
            | ``UDReiminSCGb4-Bold`` = 1296
            | ``UTMNeutra-Bold`` = 1297
            | ``UtrilloPro-DB`` = 1298
            | ``UtrilloPro-M`` = 1299
            | ``Verdana`` = 1300
            | ``Verdana-Bold`` = 1301
            | ``Verdana-Boldltalic`` = 1302
            | ``Verdana-Italic`` = 1303
            | ``VinerHandITC`` = 1304
            | ``Vivaldii`` = 1305
            | ``VladimirScript`` = 1306
            | ``Webdings`` = 1307
            | ``Wingdings2`` = 1308
            | ``Wingdings3`` = 1309
            | ``Wingdings-Regular`` = 1310
            | ``XBTitre`` = 1311
            | ``XeniaExtendedCyrillic`` = 1312
            | ``YouYuan`` = 1313
            | ``YuGothic-Bold`` = 1314
            | ``YuGothic-Light`` = 1315
            | ``YuGothic-Medium`` = 1316
            | ``YuGothic-Regular`` = 1317
            | ``YuGothicUI-Bold`` = 1318
            | ``YuGothicUI-Light`` = 1319
            | ``YuGothicLM-Regular`` = 1320
            | ``YuGothicLM-Semibold`` = 1321
            | ``YuGothicLM-Semilight`` = 1322
            | ``ZWAdobeF`` = 1323
            | ``FZCCHJW-GB1-0`` = 1324
            | ``FZCHYJW-GB1-0`` = 1325
            | ``FZCQJW-GB1-0`` = 1326
            | ``FZCSJW-GB1-0`` = 1327
            | ``FZCYJW-GB1-0`` = 1328
            | ``FZDBSJW-GB1-0`` = 1329
            | ``FZDHTJW-GB1-0`` = 1330
            | ``FZDHTK-GBK1-0`` = 1331
            | ``FZFSJW-GB1-0`` = 1332
            | ``FZGUW-GB1-0`` = 1333
            | ``FZHCJW-GB1-0`` = 1334
            | ``FZHUW-GB1-0`` = 1335
            | ``FZHPJW-GB1-0`` = 1336
            | ``FZHTJW-GB1-0`` = 1337
            | ``FZHZGBJW-GB1-0`` = 1338
            | ``FZJZJW-GB1-0`` = 1339
            | ``FZKANGJW-GB1-0`` = 1340
            | ``FZKATJW-GB1-0`` = 1341
            | ``FZKTJW-GB1-0`` = 1342
            | ``FZL2JW-GB1-0`` = 1343
            | ``FZLBJW-GB1-0`` = 1344
            | ``FZLSJW-GB1-0`` = 1345
            | ``FZLTCHK-GBK1-0`` = 1346
            | ``FZLXTJW-GB1-0`` = 1347
            | ``FZMHJW-GB1-0`` = 1348
            | ``FZNBSJW-GB1-0`` = 1349
            | ``FZNSTJW-GB1-0`` = 1350
            | ``FZPHTJW-GB1-0`` = 1351
            | ``FZPTYJW-GB1-0`` = 1352
            | ``FZPWJW-GB1-0`` = 1353
            | ``FZQTJW-GB1-0`` = 1354
            | ``FZS3JW-GB1-0`` = 1355
            | ``FZSEJW--GB1-0`` = 1356
            | ``FZSHHJW-GB1-0`` = 1357
            | ``FZSHJW-GB1-0`` = 1358
            | ``FZSJSJW-GB1-0`` = 1359
            | ``FZSSJW-GB1-0`` = 1360
            | ``FZSTJW-GB1-0`` = 1361
            | ``FZSTK-GBK1-0`` = 1362
            | ``FZSYJW-GB1-0`` = 1363
            | ``FZSZJW-GB1-0`` = 1364
            | ``FZT 儿 SJW--GB1-0`` = 1365
            | ``FZWBJW-GB1-0`` = 1366
            | ``FZXBSJW-GB1-0`` = 1367
            | ``FZXDXJW-GB1-0`` = 1368
            | ``FZXH1JW-GB1-0`` = 1369
            | ``FZXIANGUW-GB1-0`` = 1370
            | ``FZXKFW-GB1-0`` = 1371
            | ``FZXKJW-GB1-0`` = 1372
            | ``FZXKK-GBK1-0`` = 1373
            | ``FZXQJW-GB1-0`` = 1374
            | ``FZXSHJW-GB1-0`` = 1375
            | ``FZY1JW-GB1-0`` = 1376
            | ``FZY3JW-GB1-0`` = 1377
            | ``FZY3K-GBK1-0`` = 1378
            | ``FZY4JW-GB1-0`` = 1379
            | ``FZYBKSJW-GB1-0`` = 1380
            | ``FZYBXSJW-GB1-0`` = 1381
            | ``FZYHJW-GB1-0`` = 1382
            | ``FZYTJW-GB1-0`` = 1383
            | ``FZYTK-GBK1-0`` = 1384
            | ``FZYXJW-GB1-0`` = 1385
            | ``FZZBHJW-GB1-0`` = 1386
            | ``FZZDXJW-GB1-0`` = 1387
            | ``FZZHYJW-GB1-0`` = 1388
            | ``FZZQJW-GB1-0`` = 1389
            | ``FZZYJW-GB1-0`` = 1390
            | ``FZZYSK-GBK1-0`` = 1391
            | ``FZZZHUNHJW-GB1-0`` = 1392
            
        
        [<AutoOpen>]
        module _FontNamesExtension =
            type FontNames with 
                member x.FsFontName = FsFontName(x.ToString())

        let [<Literal>] ArialMT = "ArialMT"
        let [<Literal>] Arial = "Arial"

        let Arial_Regular_Names = 
            [
                FontNames.Arial
                FontNames.ArialMT
            ]

        let Arial_Bold_Names = 
            [
                FontNames.``Arial-BoldMT``
                FontNames.``Arial,Bold``
            ]


module RegisterableFonts =


    //module AlibabaPuHuiTi = 
    //    type FontWeight =
    //        | Light = 0
    //        | DemiLight = 6
    //        | Regular = 1
    //        | Medium = 2
    //        | Bold = 3
    //        | Heavy = 4

    //    let private alibabaPuHuiTi (weight: FontWeight) =
    //        let weightText =  weight.ToString()
    //        { PdfEncodings = PdfEncodings.IDENTITY_H
    //          FontFamily = "阿里巴巴普惠体-" + (weightText.Substring(0,1).ToUpper())
    //          File = FsFileInfo.create (Path.Combine(resourceDirectory.Value, @"Fonts/Alibaba-PuHuiTi/Alibaba-PuHuiTi-" + weightText + ".otf")) }

    //    let light = alibabaPuHuiTi FontWeight.Light

    //    let regular = alibabaPuHuiTi FontWeight.Regular

    //    let medium = alibabaPuHuiTi FontWeight.Medium

    //    let bold = alibabaPuHuiTi FontWeight.Bold

    //    let heavy = alibabaPuHuiTi FontWeight.Heavy

    module CommonFonts = 
        let Heiti = 
            { PdfEncodings = PdfEncodings.IDENTITY_H
              FontFamily = "黑体"
              File = FsFileInfo.create (Path.Combine(resourceDirectory.Value, @"Fonts/黑体.ttf")) }


        let Songti =
            { PdfEncodings = PdfEncodings.IDENTITY_H
              FontFamily = "宋体"
              File = FsFileInfo.create (Path.Combine(resourceDirectory.Value, @"Fonts/宋体.ttc")) }


    module Adobe =

        let AdobeHeitiStd_Regular = 
            { PdfEncodings = PdfEncodings.IDENTITY_H
              FontFamily = "AdobeHeitiStd-Regular"
              File = FsFileInfo.create (Path.Combine(resourceDirectory.Value, @"Fonts/Adobe/AdobeHeitiStd-Regular.otf")) }

    module ArialUnicode =
        
        type FontWeight =
            | Regular = 0
            | Bold = 1

        let arial_unicode (weight: FontWeight) =
            let weightText =  
                match weight with 
                | FontWeight.Regular -> "Arial Unicode MS"
                | FontWeight.Bold -> "Arial Unicode MS Bold"

            { PdfEncodings = PdfEncodings.IDENTITY_H
              FontFamily = weightText
              File = FsFileInfo.create (Path.Combine(resourceDirectory.Value, @"Fonts/Arial-Unicode/" + (weightText) + ".ttf")) }


    module Arial =

        type FontWeight =
            | Regular = 0
            | Bold = 1
            | Italic = 2
            | BoldItalic = 3

        let arial (weight: FontWeight) =
            let fontName =  
                match weight with 
                | FontWeight.Regular -> "Arial"
                | FontWeight.Bold -> "Arialbd"
                | FontWeight.BoldItalic -> "Arialbi"
                | FontWeight.Italic -> "Ariali"

            let fontFamily =
                match weight with 
                | FontWeight.Regular -> "Arial"
                | FontWeight.Bold -> "Arial Bold"
                | FontWeight.BoldItalic -> "Arial Bold Italic"
                | FontWeight.Italic -> "Arial Italic"

            { PdfEncodings = PdfEncodings.CP1252
              FontFamily = fontFamily
              File = FsFileInfo.create (Path.Combine(resourceDirectory.Value, @"Fonts/Arial/" + (fontName) + ".ttf")) }


    module YaHei =
        type FontWeight =
            | Light = 0
            | Regular = 1
            | Bold = 2

        [<RequireQualifiedAccess>]
        module FontWeight = 
            let asCommonFontWeight = function
            | FontWeight.Light -> CommonFontWeight.Light
            | FontWeight.Regular -> CommonFontWeight.Regular
            | FontWeight.Bold -> CommonFontWeight.Bold



        let yaHei (weight: FontWeight) =
            let weightText = 
                match weight with 
                | FontWeight.Bold 
                | FontWeight.Light ->
                    sprintf $"Microsoft YaHei UI {weight.ToString()}"
                | FontWeight.Regular -> "Microsoft YaHei UI"

            let fontName =
                match weight with 
                | FontWeight.Bold -> "msyhbd.ttc"
                | FontWeight.Light -> "msyhl.ttc"
                | FontWeight.Regular -> "msyh.ttc"

            { PdfEncodings = PdfEncodings.IDENTITY_H
              FontFamily = weightText
              File = FsFileInfo.create (Path.Combine(resourceDirectory.Value, @"Fonts/微软雅黑/" + fontName)) }




    //module SiYuanHeiTi =
    //    type FontWeight =
    //        | Light = 0
    //        | DemiLight = 6
    //        | Regular = 1
    //        | Medium = 2
    //        | Bold = 3
    //        | Black = 5

    //    let siyuanHeiTi (weight: FontWeight) =
    //        let weightText =  
    //            match weight with 
    //            | FontWeight.Bold
    //            | FontWeight.Black -> "Noto Sans S Chinese " + (weight.ToString()) + " Bold"
    //            | _ -> "Noto Sans S Chinese " + (weight.ToString())

    //        { PdfEncodings = PdfEncodings.IDENTITY_H
    //          FontFamily = weightText
    //          File = FsFileInfo.create (Path.Combine(resourceDirectory.Value, @"Fonts/思源黑体/NotoSansHans-" + (weight.ToString()) + ".otf")) }

     


    let findRigisterableFont (fontName: string) =
        match fontName with 
        | String.EqualIC "SimSun" -> Result.Ok CommonFonts.Songti
        | String.EqualIC "ArialMT" -> Result.Ok (Arial.arial (Arial.FontWeight.Regular))
        | String.EqualIC "Arial" -> Result.Ok (Arial.arial (Arial.FontWeight.Regular))
        | String.EqualIC "Arial,Bold" -> Result.Ok (Arial.arial (Arial.FontWeight.Bold))
        | _ -> Result.Error (sprintf "Cannot find RigisterableFont by %s" fontName)